version: "3.8"

services: 
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - zomato_mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
     test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
     interval: 5s
     timeout: 5s
     retries: 10

  backend:
    build: .
    container_name: zomato_clone
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 5000
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  zomato_mongo: